### PR TITLE
Fix config include path

### PR DESCRIPTION
**Pull request by gbirke**
The path was one directory too shallow, the config was looked for in
`vendor` not the appplication "root" directoy.

### CODE REVIEW

**Comment by manicki** [comment]
Shouldn't applications use `vendor/bin/cli-config.php` and not to `vendor/wmde/fundraising-store/cli-config.php`?
If so, path is correct, no?

**Comment by gbirke** [comment]
Applications should either use `cli-config.php` (in application root) or `config/cli-config-php` (See https://github.com/doctrine/doctrine2/blob/master/bin/doctrine.php#L33 ). Re-using `vendor/wmde/fundraising-store/cli-config.php` is indeed bad practice, as it forces all applications to have a `db-config-local.php` with constant definitions in their root directory.

I'll close this, fix `fundraising-backend` by creating a  `cli-config.php` and make a new request that removes the parent directory lookup.

**Comment by manicki** [comment]
> Applications should either use cli-config.php (in application root) or config/cli-config-php (See https://github.com/doctrine/doctrine2/blob/master/bin/doctrine.php#L33 ).

It might be just a matter of interpretation but I read line you linked to as "cli-config.php has to be in the same directory where doctrine console is run or in its config subdirectory". Which is not necessarily the root dir of application using Doctrine (`vendor/bin` being sort of a default).

I am not really up-to-date so I don't know what you are fixing in `fundraising-backend` but I'd rather vote for keeping Doctrine-related files (here cli-config.php) in the same place where other doctrine things are, ie. under `vendor/bin`, not some over there, some in the root dir.

**Comment by gbirke** [comment]
IMO `vendor/bin` shouldn't be touched by anyone but composer and should only contain  executable php scripts and not config information.

The [fundraising-backend changes](https://github.com/wmde/fundraising-backend/pull/204) use FundraisingStore 2.0 and I've just [added a `cli-config.php` there](https://github.com/wmde/fundraising-backend/pull/204/commits/ff040ba395a0d1b9631610838f3cf1521aeba819), the changes no longer depend on this PR being merged.  `cli-config.php` fundraising-backend is only needed by travis so it could be moved to `build`.

**Comment by manicki** [comment]
> IMO vendor/bin shouldn't be touched by anyone but composer and should only contain executable php scripts and not config information.

That file is indeed installed by Composer

> cli-config.php fundraising-backend is only needed by travis so it could be moved to build

You would probably also use it when you clone the `fundraising-backend` repository to create database tables, same as Travis does in every build. OR when new version of store component is released and any app using store switches to a new version and you need to update schema.

AFAIR the reason this cli config file was added as [a vendor binary](https://getcomposer.org/doc/articles/vendor-binaries.md) is it is required by Doctrine console, and the doctrine console allows such stuff as creating db tables, updating db schema when entity classes change etc.
Without this file installed from this component under `myfunapp/vendor/bin` when you run `composer install` in `myfunaupp` you would end up having similar files in `myfunapp` and every single repository depending on FundraisingStore. Should anything change in the file (quite unlikely but let's say some super breaking change in Doctrine) you would end up updating N repositories instead of having to update only this one and making transition possibly even invisible for users of FundraisingStore.

Now I see that Travis builds failed here: https://travis-ci.com/wmde/fundraising-backend/builds/30719359. Looking very briefly at the log it seems odd why it is looking for the file in the wrong dir. Still, I am not sure it this should be "fixed" be having N local copies of cli-config.

**Comment by manicki** [comment]
Bah, I must have been tired yesterday afternoon. Now I see you guys have obviously changed the way DB config is stored so the "common" cli-config is no longer valid (as long as the old "frontend" app is not buried and "backend" app does not switch to a similar DB config file as new "frontend" uses - which might or might not be sane, might not even be possible).
So in such case having this cli-config as a vendor binary in this repo makes no sense (but this is a breaking change as @JeroenDeDauw said in the other ticket).
My apologies for creating confoosion.

That said I still:
 - have no idea why Travis builds for "fundraising-backend" fail due to looking for the old-format config (which would work for that repo, no?) in a wrong dir?
 - am not entirely convinced that root directory of each app using store is the best location for such file. "build" (as in "stuffs meant for CI") does not convince me either, as I said above I believe "normal" users would also want to use it at least once in their work with each app.

**Pull request closed without merging**
