### PR TITLE
Switch to PHP 7.1 and update PHPUnit and PHPCS

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Need to update the MySQL stuff for Travis. Unrelated to this PR; broken on master due to TravisCI changes

**Comment by KaiNissen** [comment]
Fixed mysql stuff in #124.

**Comment by KaiNissen** [comment]
Where is the review button? Anyway, I do approve this.

**Comment by JeroenDeDauw** [comment]
Awesome, thanks for fixing! \o/

**Pull request merged**
