### PR TITLE
add payment type to membership application

### PR DESCRIPTION
**Pull request by KaiNissen**

### CODE REVIEW

**Comment by manicki** [comment]
+1

**Comment by JeroenDeDauw** [comment]
+1

**Comment by KaiNissen** [comment]
Any specific reason why nobody dares to hit the green button? @gbirke maybe?

**Comment by JeroenDeDauw** [comment]
What are the implications of this change? Presumably some update thinghy needs to be run when pulling it in? And it won't break any existing data?

**Comment by manicki** [comment]
This is just adding a column, so I believe you'd only need to run Doctrine console `schema-update` or whatever it is called, and that would be it. It would not change existing data apart from adding `BEZ` to all of them (which is valid).

OK, I am merging this and I hope all of the things are not going to explode.

@KaiNissen I assume you need this rather ASAP for some new feature(s) required for the banner campaign. Should we tag version 2.1 right away (possibly including Gabriel's change to cli-config)? Or are the more things coming up, so we should rather wait with the release?

**Comment by gbirke** [comment]
I'd have waited until the databases are updated (sorry I did not react earlier), because now things will explode as soon as someone updates the dependency. But I'll update the database today.

Regarding the new release, I've created Phabricator ticket https://phabricator.wikimedia.org/T147624 because there needs at least to be some changes to the README before tagging.

**Comment by manicki** [comment]
> I'd have waited until the databases are updated (sorry I did not react earlier), because now things will explode as soon as someone updates the dependency. But I'll update the database today.

But nothing should explode as long this is not tagged and production servers updated to use the new version, right? So I don't need to hide under the desk from raging fundraisers?

> Regarding the new release, I've created Phabricator ticket https://phabricator.wikimedia.org/T147624 because there needs at least to be some changes to the README before tagging.

Sure, that's why I asked if we want to tag it? If so, I/someone else more familiar with the current state of the library would do the changes and then the new release is released.

**Comment by gbirke** [comment]
Yes, you're right. No one will rage and thank you for jumping in when this PR got no attention from the FUN team, I really appreciate your commitment and help.

**Comment by JeroenDeDauw** [comment]
We should probably also figure out how we want to deal with changes like these. They require some action but are not really breaking changes warranting a mayor release. Yet if we tag as `2.1.0`, `composer update` will pull it in if we have `~2.0`. So perhaps we ought to switch to `~2.0.0`, `~2.1.0`, etc, so we only pull in fixes (that should not need running the update script) unless we explicitly bump the store version...

**Comment by TillWMDE** [comment]
@gbirke I am closer than you think and I read carefully!

**Comment by JeroenDeDauw** [comment]
frown

**Pull request merged**
