### PR TITLE
English properties

### PR DESCRIPTION
**Pull request by gbirke**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I think it's a bad idea to give branches names of valid releases. Composer will treat them as such. In case the 2.0.0 one here is meant to actually be a branch for the 2.x series, then naming it 2.x or 2.0.x is better. (I suspect it makes more sense to just change master to 2.x, as I'm not aware of any work we want to continue doing on 1.x.)

**Comment by JeroenDeDauw** [comment]
I've now seen #34 and figure you misunderstood what @wmde-manicki suggested. The branch alias he mentioned is this thing: https://github.com/wmde/FundraisingStore/blob/4f3ee7e1af4a2b5bb1b7b9a1a42b748e3820332d/composer.json#L20-L22

**Comment by wmde-manicki** [comment]
Oh, sorry, I didn't notice this PR earlier and I am afraid I might have caused closing

**Comment by gbirke** [comment]
Ok the new branch is now called 2.x

**Comment by JeroenDeDauw** [comment]
No such branch is needed. As @wmde-manicki pointed out, you just need to update the branch alias defined in composer.json when merging this into master.

**Pull request merged**
