### PR TITLE
5.1.0 release

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Did not mention `DonationPayment` as I figure this class is not meant to be used directly from outside of this component.

PS: wondering why `DonationPayment` is not in the `DonationPayments` NS. Not that it matters much esp if indeed package private.

### CODE REVIEW

**Comment by gbirke** [comment]
It's a common pattern in PHP projects to have the abstract class/interface at the same level as the namespace of the classes that implement it. At least that's where I'd look first.

The is a version mismatch here, the `@since` tag in the classes says `6.0`. Which leads to the question what version number to use. From a PHP API interface standpoint, this is a 5.1 release, as only new methods and classes are added and no behavior changes. But the database must be changed/migrated which makes this a BC break in my opinion, which justifies a major version. What do you think?

**Comment by JeroenDeDauw** [comment]
> It's a common pattern in PHP projects to have the abstract class/interface at the same level as the namespace of the classes that implement it. At least that's where I'd look first.

Did you forget a word somewhere? Cause what you did is put the interface in the namespace above the one in which you have the implementations.

**Comment by JeroenDeDauw** [comment]
Re version:

Good catch. I also think this should be a major bump, since otherwise the users of this code will break if they pull in the new stuff. (At least they will when they make use of it, not sure if they will when they do not.)

**Comment by gbirke** [comment]
>> It's a common pattern in PHP projects to have the abstract class/interface at the same level as the namespace of the classes that implement it. At least that's where I'd look first.

> Did you forget a word somewhere? Cause what you did is put the interface in the namespace above the one in which you have the implementations.

```
root
  +-- interface
  +-- namespace
      +-- Impl1
      +-- Impl2
```

Depending on how you look at it, `interface` is "above" the implementations or "at the same level" (`root`) as the *namespace* of the implementations.

**Comment by JeroenDeDauw** [comment]
Right, I misread what you wrote. Fine by me

**Comment by JeroenDeDauw** [comment]
https://github.com/wmde/FundraisingStore/pull/137

**Pull request closed without merging**
