### PR TITLE
Improve name of $name field

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by manicki** [comment]
+1

**Comment by KaiNissen** [comment]
Errr, why rename it?

**Comment by JeroenDeDauw** [comment]
To encode the knowledge we have about it. Else it can continue to confuse people, and you'll probably have me ask again in a few months what the deal with this field is.

**Comment by KaiNissen** [comment]
Yes, I see the point. I'd consider a TODO tag sufficient.

**Pull request merged**
