### PR TITLE
Remove EntityManagerProvider class and make cli-config installed as a vendor binary

### PR DESCRIPTION
**Pull request by wmde-manicki**
Remove unnecessary class introduced in https://github.com/wmde/FundraisingStore/pull/8

### CODE REVIEW

**Comment by wmde-manicki** [comment]
Right, I moved it to `vendor/bin/config`. Now the Doctrine console may (and must) be run from `vendor/bin`.

**Comment by KaiNissen** [comment]
Putting it into `vendor/bin/` is a good idea. But the file is now in `vendor/wmde/fundraising-store/vendor/bin/config/`. I think, composer creates symlinks to files by using something like `"bin": [ "path/to/cli-config.php" ]` in composer.json. How about putting the file into `config/` or `bin/` and configure composer to create a symlink from there?

**Comment by wmde-manicki** [comment]
Sorry, I mixed things up. Will fix this. Of course, we want to have it installed to `vendor/bin` after installing the package, that makes perfect sense

**Comment by wmde-manicki** [comment]
I have removed the entirely wrong commit https://github.com/wmde/FundraisingStore/commit/cf6ace5576440f986e2f4b5d0d5675d0389d81b3 from this and renamed the pull request as we are going to do more than just removing the class.
I am not totally happy with passing `config.ini.template` along but don't know what would be better way to provide db credentials. Will appreciate suggestions.

**Comment by KaiNissen** [comment]
Yes, also the the web server needs to be configured to prevent browser access to it, unless we put it to a location outside of the web root.

We have php configuration files, that also contain the necessary information to access the database. How about we change them to be in accordance with each other and include them in the cli-config.php? The only relevant differences are their file names and the constant name for the password.

**Comment by wmde-manicki** [comment]
Good point. Did the changes, related  pull request are https://github.com/wmde/fundraising/pull/544 and https://github.com/wmde/fundraising-backend/pull/123

**Pull request merged**
