### PR TITLE
Prefix entity names with Doctine to avoid naming confoosion

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
As per https://github.com/wmde/FundraisingStore/issues/72

Doing just these two for now as they are the most obvious. Curious
to what your thoughts are on doing this for all others as well.

### CODE REVIEW

**Comment by gbirke** [comment]
I've voiced my opinion and its evolution in #72. If @KaiNissen has no objections, I'd merge this.

**Comment by KaiNissen** [comment]
I do not object.

**Comment by KaiNissen** [comment]
I do not object.

**Comment by JeroenDeDauw** [comment]
Rebased

**Comment by gbirke** [comment]
We should make this part of a 4.0 release, because otherwise our existing applications, which depend on 3.0-dev, will break without modification.

**Comment by JeroenDeDauw** [comment]
Ugh... that's why you don't make them depend on a dev version :)

**Comment by JeroenDeDauw** [comment]
I concur with waiting till a later major release given the dev-dependency.

**Pull request closed without merging**
